org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false

mod_id=kltyton_temple
mod_name=KltytonTemple
mod_license=MIT
mod_version=1.0.0
mod_group_id=io.github.kltyton.temple
mod_authors=kltyton
mod_description=A multi-version and multi-loader Minecraft development template.

temple_default_target=forge-1.20.1
