loader=forge
datagen_task=runData
minecraft_version=1.19.2
minecraft_version_range=[1.19.2]
loader_version=43.5.0
loader_version_range=[43,)
fml_version_range=[43,)
java_version=17
gradle_java_version=21
moddev_version=2.0.142
publish_plugin_version=2.1.1
shared_sources=common,versions/1.19.2,loaders/forge
ci_enabled=true
