loader=neoforge
datagen_task=runData
minecraft_version=26.2.0
minecraft_version_range=[26.2.0]
loader_version=26.2.0.88
loader_version_range=[26.2.0,)
fml_version_range=[11,)
java_version=25
gradle_java_version=25
moddev_version=2.0.147
publish_plugin_version=2.1.1
shared_sources=common,versions/26.2.0,loaders/neoforge
ci_enabled=true
